project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!local/"

execute:
  freeze: auto  # re-render only when source changes

website:
  title: "PSQT-GLMM"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/stat-teaching/psqt-glmm
  page-footer: "Master PSQT - Quantitative Psychology"
        
author: 
  - name: "Filippo Gambarota"
    email: filippo.gambarota@unipd.it
    twitter: fgambarota
    github: filippogambarota
    orcid: "0000-0002-6666-1747"
institute: "University of Padova"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: "https://raw.githubusercontent.com/filippogambarota/bib-database/main/references.bib"
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl"