{
  "hash": "74c28ef5cd4a5498ccb9472dae3bc559",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Introduzione ai Linear Mixed-Effects Models\n---\n\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lme4)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(glmmTMB)\ndat <- sleepstudy\n# ?sleepstudy\n```\n:::\n\n\nCominciamo direttamente con un esempio con il dataset `sleepstudy` del pacchetto `lme4`^[Vedremo che questo pacchetto è quello più utilizzato e completo per implementare modelli con effetti random in R].\n\nIl dataset riguarda l'impatto della deprivazione da sonno nei tempi di reazione di un gruppo di soggetti.\n\n> The average reaction time per day (in milliseconds) for subjects in a sleep deprivation study. Days 0-1 were adaptation and training (T1/T2), day 2 was baseline (B); sleep deprivation started after day 2.\n\nPartiamo esplorando il dataset:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Reaction Days Subject\n1      250    0     308\n2      259    1     308\n3      251    2     308\n4      321    3     308\n5      357    4     308\n6      415    5     308\n\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Reaction Days Subject\n175      287    4     372\n176      330    5     372\n177      334    6     372\n178      343    7     372\n179      369    8     372\n180      364    9     372\n\n```\n\n\n:::\n:::\n\n\nVediamo che `Reaction` è il tempo di reazione in millisecondi, `Days` sono i giorni di deprivazione e `Subject` è un codice univoco per ogni partecipante.\n\nVediamo la distribuzione marginale dei tempi di risposta:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist(dat$Reaction, breaks = 20)\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nVediamo il numero di giorni che abbiamo di deprivazione. Per ogni giorno di deprivazione (massimo 9) abbiamo 18 soggetti.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(dat$Days)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 0  1  2  3  4  5  6  7  8  9 \n18 18 18 18 18 18 18 18 18 18 \n\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(dat$Subject)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n308 309 310 330 331 332 333 334 335 337 349 350 351 352 369 370 371 372 \n 10  10  10  10  10  10  10  10  10  10  10  10  10  10  10  10  10  10 \n\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(soggetti = dat$Subject, giorni = dat$Days)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        giorni\nsoggetti 0 1 2 3 4 5 6 7 8 9\n     308 1 1 1 1 1 1 1 1 1 1\n     309 1 1 1 1 1 1 1 1 1 1\n     310 1 1 1 1 1 1 1 1 1 1\n     330 1 1 1 1 1 1 1 1 1 1\n     331 1 1 1 1 1 1 1 1 1 1\n     332 1 1 1 1 1 1 1 1 1 1\n     333 1 1 1 1 1 1 1 1 1 1\n     334 1 1 1 1 1 1 1 1 1 1\n     335 1 1 1 1 1 1 1 1 1 1\n     337 1 1 1 1 1 1 1 1 1 1\n     349 1 1 1 1 1 1 1 1 1 1\n     350 1 1 1 1 1 1 1 1 1 1\n     351 1 1 1 1 1 1 1 1 1 1\n     352 1 1 1 1 1 1 1 1 1 1\n     369 1 1 1 1 1 1 1 1 1 1\n     370 1 1 1 1 1 1 1 1 1 1\n     371 1 1 1 1 1 1 1 1 1 1\n     372 1 1 1 1 1 1 1 1 1 1\n\n```\n\n\n:::\n:::\n\n\nQuindi abbiamo un dataset completo, senza valori mancanti. Tutti i soggetti hanno tutte le osservazioni. Ora vediamo qualche statistica descrittiva del tempo (in ms) in funzione dei giorni di deprivazione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat |> \n    ggplot(aes(x = factor(Days), y = Reaction)) +\n    geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nSi vede chiaramente un pattern, dove al crescere della deprivazione crescono chiaramente i tempi di reazione. Ovviamente è presente della variabilità ma la mediana del tempo cresce chiaramente.\n\nVediamo ora la situazione per ogni soggetto. Ogni linea è il trend di ogni soggetto. Vediamo che nonostante ci sia variabilità tra soggetti, il pattern è abbastanza comune per tutti : al crescere della deprivazione da sonno, si abbassano i tempi di reazione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat |> \n    ggplot(aes(x = Days, y = Reaction)) +\n    geom_line(aes(group = Subject))\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nOra, proviamo a stimare con un modello statistico questo trend che vediamo ad occhio dove i tempi di reazione aumentano. Se lo affrontiamo con gli strumenti che conosciamo finora ovvero i modelli lineari, possiamo implementare un modello di questo tipo:\n\n$$\n\\mbox{RT}_{i} = \\beta_0 + \\beta_1 \\mbox{Days}_i + \\epsilon_i\n$$\n\nPossiamo anche implementarlo direttamente in R:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_lm <- lm(Reaction ~ Days, data = dat)\nsummary(fit_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Reaction ~ Days, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-110.85  -27.48    1.55   26.14  139.95 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   251.41       6.61   38.03  < 2e-16 ***\nDays           10.47       1.24    8.45  9.9e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 47.7 on 178 degrees of freedom\nMultiple R-squared:  0.286,\tAdjusted R-squared:  0.282 \nF-statistic: 71.5 on 1 and 178 DF,  p-value: 9.89e-15\n\n```\n\n\n:::\n:::\n\n\nPossiamo intepretare i parametri in modo classico:\n\n- $\\beta_0$: al tempo 0 (Days = 0) il tempo di reazione medio è 251.405 ms\n- $\\beta_1$: per ogni giorno che passa di deprivazione, il tempo di reazione medio aumenta di 10.467 ms\n\nQuesto modello sta cercando di stimare la relazione tra Days e Reaction $\\beta_1$ utilizzando tutte le osservazioni $i$ del dataset. Notate qualcosa di strano?\n\nDa nessuna parte nel modello si tiene conto del fatto che le righe del dataset sono **raggruppate** in base al soggetto. Ogni soggetto ha 10 righe (0-9) che indicano il suo tempo di reazione. Questo comporta che le righe non sono indipendenti ovvero che le righe associate al soggetto 308 sono (probabilmente) più simili tra loro rispetto alle righe di un'altro soggetto.\n\nIn termini pratici, se un soggetto parte a tempo 0 con un tempo di reazione alto mentre un'altro soggetto parte con un tempo di reazione basso è probabile che anche le osservazioni per gli altri tempi siano in media più alte/basse.\n\nVediamo un grafico con tutte le osservazioni per ogni soggetto. Il punto rosso rappresenta la media di ogni soggetto.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat |> \n    ggplot(aes(x = Subject, y = Reaction)) +\n    geom_point(size = 2) +\n    stat_summary(fun = mean, geom = \"point\", size = 5, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/fig-cluster-means-1.png){#fig-cluster-means fig-align='center' width=672}\n:::\n:::\n\n\nDa questo grafico vediamo che:\n\n- ogni soggetto ha la sua media e le medie dei soggetti sono diverse tra loro\n- le osservazioni di un soggetto sono più simili tra loro rispetto ad osservazioni di due soggetti diversi\n\nProviamo ad unire i due plot precedenti facendo vedere variazioni di media e anche dell'effetto dei giorni di deprivazione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(Reaction ~ Days, data = dat, type = \"b\")\npoints(dat$Days[dat$Days == 0], dat$Reaction[dat$Days == 0], col = \"red\", pch = 19, cex = 2)\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nDal grafico si vede che ogni soggetto ha il suo punto di partenza. Inoltre ogni soggetto ha il suo trend che varia in modo importante. \n\nIl modello che abbiamo scritto prima ignora completamente il fatto che le misurazioni siano raggruppate (*nested*) nel soggetto. Ignora anche che ogni soggetto sembra avere, oltre alla sua baseline, anche la sua pendenza/slope rispetto all'effetto dei giorni.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat |> \n  ggplot(aes(x = Days, y = Reaction)) +\n  geom_point(size = 3) +\n  geom_line(aes(group = Subject)) +\n  geom_smooth(method = \"lm\", se = FALSE, lwd = 2)\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nProviamo, invece di fare un modello complessivo, a fare un modello per ogni soggetto. Quindi facciamo con `lm` lo stesso modello ma individualmente per ogni soggetto. Possiamo usare la funzione `lme4::lmList()`. Questi sono i parametri stimati, $\\beta_0$ e $\\beta_1$ per ogni soggetto. Confrontiamoli con quelli che abbiamo stimato dal modello completo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfitl <- lmList(Reaction ~ Days | Subject, data = dat)\n# aggiungiamo quello completo\nfitl <- c(fitl, \"full\" = list(fit_lm))\nfitl <- do.call(rbind, lapply(fitl, coef))\nfitl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     (Intercept)  Days\n308          244 21.76\n309          205  2.26\n310          203  6.11\n330          290  3.01\n331          286  5.27\n332          264  9.57\n333          275  9.14\n334          240 12.25\n335          263 -2.88\n337          290 19.03\n349          215 13.49\n350          226 19.50\n351          261  6.43\n352          276 13.57\n369          255 11.35\n370          210 18.06\n371          254  9.19\n372          267 11.30\nfull         251 10.47\n\n```\n\n\n:::\n:::\n\n\nChiaramente c'è una differenza importante, che possiamo visualizzare anche graficamente. La retta rossa è il modello completo (uguale per tutti), quella blu è il modello per soggetto. Per molti soggetti il modello complessivo è una buona approssimazione dell'effetto individuale, per altri meno.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat |> \n  ggplot(aes(x = Days, y = Reaction)) +\n  geom_point() +\n  geom_line(aes(group = Subject)) +\n  facet_wrap(~Subject) +\n  geom_abline(intercept = coef(fit_lm)[1], slope = coef(fit_lm)[2], lwd = 1, col = \"red\") +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/fig-prova-1.png){#fig-prova fig-align='center' width=672}\n:::\n:::\n\n\nQuesti due approcci che abbiamo usato hanno un nome specifico e si chiamano:\n\n- **complete pooling**: modello che ignora il fatto che ci sono soggetti diversi con osservazioni nested. Stima una relazione unica ignorando la correlazione tra osservazioni dello stesso soggetto.\n- **no pooling**: modello(i) che ignorano in un certo senso il trend medio e preferiscono avere un parametro (o meglio due, $\\beta_0$ e $\\beta_1$) per ogni soggetto.\n\nPossiamo trovare pregi e difetti di entrambi. Proviamo ad elencarne alcuni:\n\n- il **complete pooling** non tiene conto del cluster/soggetto. Vedremo dopo meglio le conseguenze ma sta ignorando una componente fondamentale della struttura dati. Il \"vantaggio\" è che a prescindere dal numero di soggetti ed osservazioni, il numero di parametri stimati è sempre minimo. In questo caso solo 3, $\\beta_0$, $\\beta_1$ e $\\sigma^2_{\\epsilon}$.\n- il **no pooling**: tiene, forse troppo, conto del fatto che ci sono cluster/soggetti tanto che decide di stimare un intero modello per ognuno. Il vantaggio è che teniamo conto delle differenze che abbiamo visto anche ad occhio, lo svantaggio è che il numero di parametri cresce tantissimo all'aumentare dei cluster/soggetti e alla complessità del modello.\n\nPotete immaginare che un approccio sensato stia nel mezzo, ma prima di vedere più formalmente come implementarlo, facciamo un passo indietro riguardo il **complete pooling** ed il fatto di ignorare i cluster.\n\nMentre è chiaro che stimare un parametro per soggetto sia una scelta problematica, il problema di ignorare i soggetti/cluster è meno chiaro. La questione si esprime bene in termini di informazione.\n\nImmaginate di misurare i tempi di reazione di un soggetto, 9 volte, oppure di misurare i tempi di reazione in 9 soggetti diversi una volta. E' chiaro che:\n\nImmaginate due situazioni: misuriamo i tempi di reazione di uno stesso soggetto 9 volte, oppure misuriamo i tempi di reazione di 9 soggetti diversi una sola volta ciascuno. In entrambi i casi abbiamo 9 osservazioni, ma non abbiamo la stessa quantità di informazione indipendente.\n\nNel primo caso, le osservazioni sono parzialmente ridondanti: se un soggetto è mediamente molto veloce, è probabile che tutte le sue misurazioni tendano a essere più veloci. Le 9 osservazioni ci informano molto bene su quel soggetto, ma meno sulla variabilità generale tra soggetti.\n\nNel secondo caso, invece, ogni osservazione proviene da un soggetto diverso. Le osservazioni sono quindi meno dipendenti tra loro e portano più informazione sulla popolazione di soggetti da cui sono state estratte.\n\nIl problema nasce quando trattiamo le 9 misurazioni dello stesso soggetto come se fossero equivalenti a 9 soggetti diversi. In quel caso sovrastimiamo la quantità di informazione indipendente contenuta nei dati.\n\nOra riprendiamo il grafico precedente:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/fig-cluster-means-1.png){#fig-cluster-means fig-align='center' width=672}\n:::\n:::\n\n\nOra, se le medie dei soggetti sono diverse tra loro automaticamente le osservazioni saranno più correlate. Avere una baseline diversa comporta che le osservazioni del soggetto 308 tenderanno ad essere maggiori (e più simili tra loro) di quelle del soggetto 309.\n\nQuindi, la variabilità tra le medie dei soggetti (cluster) è un indice di quanto sono correlati. In modo grezzo e non formalmente corretto proviamo a calcolare un indice chiamiamolo $\\rho$. Dove $\\sigma^2_{\\text{id}}$ è la variabilità dovuta ai soggetti e $\\sigma^2_{y}$ è la variabilità totale.\n\n$$\n\\frac{\\sigma^2_{\\text{id}}}{\\sigma^2_{y}}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigma2y <- var(dat$Reaction)\nsigma2id <- var(tapply(dat$Reaction, dat$Subject, mean))\nsigma2id / sigma2y\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.465\n\n```\n\n\n:::\n:::\n\n\nQuindi il 47% circa, della varibilità totale è dovuta al raggruppamento delle osservazioni per soggetto. Dopo lo vedremo più formalmente ma questo indice si chiama **intraclass correlation** (ICC) e rappresenta appunto una stima della correlazione tra osservazioni nello stesso cluster. Prima di passare al modello più formale vediamo l'impatto dell'ICC:\n\n$$\nn_{\\text{eff}} = \\frac{km}{1 + (m - 1) \\rho}\n$$\n\nDove $m$ è il numero totale di osservazioni (medio) in ogni cluster e $k$ è il numero di cluster. Quindi $n = km$ è il numero totale di osservazioni nel dataset e $\\rho$ è l'ICC che abbiamo calcolato prima^[Questo non è il calcolo preciso, quello più accurato lo faremo dopo con le stime del modello ma può essere inteso come un'approssimazione]. Questa formula calcola quello che si chiama *effective sample size* ovvero il numero di osservazioni effettive una volta che teniamo conto della correlazione.\n\nCalcoliamolo nel nostro caso e poi vediamo alcuni scenari:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nneff <- function(k, m, r) (k*m)/(1 + (m-1)*r)\n\nk <- length(unique(dat$Subject))\nm <- mean(tapply(dat$Reaction, dat$Subject, length))\nr <- sigma2id / sigma2y\n\n# osservazioni totali\nk * m \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 180\n\n```\n\n\n:::\n\n```{.r .cell-code}\n# osservazioni effettive\nneff(k, m, r)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 34.7\n\n```\n\n\n:::\n:::\n\n\nQuindi abbiamo un numero effettivo di osservazioni di circa 35 a fronte di un totale di 180 che è una riduzione importante. Questo è il motivo principale per cui usare un modello lineare che ignora la clusterizzazione delle osservazioni può essere estremamente problematico. Vediamo qualche scenario:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot() +\n    stat_function(fun = function(x) neff(k, m, x)) +\n    xlab(\"ICC\") +\n    ylab(\"Effective Sample Size\")\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nCome vedete, quando ICC = 0 non abbiamo perdita di informazione. Questo è quello che il modello lineare semplice assume normalmente. Quando, nel caso estremo, ICC = 1 allora il numero di osservazioni effettive corrisponde al numero di cluster. In altri termini tutte le osservazioni all'interno del cluster sono esattamente identiche e quindi $m$ osservazioni valgono come 1.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# funzione per simulare dati con un certo icc\nsimICC <- function(k, m, icc){\n  obs <- rep(1:k, each = m)\n  ym <- rnorm(k, 0, sqrt(icc))\n  y <- ym[obs] + rnorm(k*m, 0, sqrt(1 - icc))\n  data.frame(id = obs, y = y, icc = icc)\n}\n\nicc <- c(0, 0.5, 0.8)\n\nlapply(icc, function(x) simICC(10, 50, x)) |> \n    do.call(rbind, args = _) |> \n    ggplot(aes(x = id, y = y)) +\n    facet_wrap(~icc) +\n    geom_point() +\n    stat_summary(fun = mean, col = \"red\", geom = \"point\", size = 4) +\n    xlab(\"Soggetti\") +\n    ylab(\"Y\")\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nCome vedete in questi dati simulati, all'aumentare dell'ICC aumenta la variabilità tra le medie dei cluster/soggetti e inoltre la variabilità dentro i cluster diminuisce perchè le osservazioni tendono a diventare più simili tra loro.\n\nIn termini pratici, il problema più importante di ignorare il clustering delle osservazioni è legato alla sovrastima (fittizia) della precisione (quindi sottostima dell'errore standard) del modello lineare classico. Immaginiamo che il modello stia stimando una semplice media il cui errore standard è:\n\n$$\n\\text{SE}_{\\bar y} = \\frac{\\hat \\sigma^2_y}{\\sqrt{n}} \\quad n = km\n$$\n\nQuindi proviamo a fare una simulazione con i nostri dati stimando i tempi di reazione medi del nostro dataset.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# media generale\n(ybar <- mean(dat$Reaction))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 299\n\n```\n\n\n:::\n\n```{.r .cell-code}\nn <- nrow(dat)\n\n# errore standard come lo stimerebbe il modello lm()\nsd(dat$Reaction) / sqrt(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.2\n\n```\n\n\n:::\n\n```{.r .cell-code}\n# errore standard tenendo conto di ICC\nn_eff <- neff(k, m, r)\nsd(dat$Reaction) / sqrt(n_eff)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.56\n\n```\n\n\n:::\n:::\n\n\nL'errore standard è drasticamente più grande perchè teniamo conto dell'informazione effettiva al netto della correlazione (ICC). Questo vale per qualsiasi parametro in un modello dove ignoriamo la presenza dei cluster (e ovviamente ICC > 0).\n\nVediamo adesso più formalmente come espandere il modello lineare che conosciamo. L'idea di base che dobbiamo incorporare è quella del clustering. Il nostro modello ne deve tenere conto, quindi dimentichiamoci l'idea del **complete-pooling**. Se volessimo introdurre l'idea del **no-pooling** che tiene conto (all'estremo) del clustering dobbiamo stimare un parametro per soggetto:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_pool <- lm(Reaction ~ 1, data = dat)\nfit_no_pool <- lm(Reaction ~ 0 + Subject, data = dat)\n\nsummary(fit_pool)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Reaction ~ 1, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-104.18  -43.13   -9.86   38.24  167.85 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    298.5        4.2    71.1   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 56.3 on 179 degrees of freedom\n\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_no_pool)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Reaction ~ 0 + Subject, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-115.74  -24.60   -3.72   23.00  146.86 \n\nCoefficients:\n           Estimate Std. Error t value Pr(>|t|)    \nSubject308      342         14    24.4   <2e-16 ***\nSubject309      215         14    15.4   <2e-16 ***\nSubject310      231         14    16.5   <2e-16 ***\nSubject330      303         14    21.7   <2e-16 ***\nSubject331      309         14    22.1   <2e-16 ***\nSubject332      307         14    22.0   <2e-16 ***\nSubject333      316         14    22.6   <2e-16 ***\nSubject334      295         14    21.1   <2e-16 ***\nSubject335      250         14    17.9   <2e-16 ***\nSubject337      376         14    26.8   <2e-16 ***\nSubject349      276         14    19.7   <2e-16 ***\nSubject350      314         14    22.4   <2e-16 ***\nSubject351      290         14    20.7   <2e-16 ***\nSubject352      337         14    24.1   <2e-16 ***\nSubject369      306         14    21.9   <2e-16 ***\nSubject370      292         14    20.8   <2e-16 ***\nSubject371      295         14    21.1   <2e-16 ***\nSubject372      318         14    22.7   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 44.3 on 162 degrees of freedom\nMultiple R-squared:  0.981,\tAdjusted R-squared:  0.979 \nF-statistic:  462 on 18 and 162 DF,  p-value: <2e-16\n\n```\n\n\n:::\n:::\n\n\nPer incorporare il cluster abbiamo capito che il parametro critico è ICC o comunque la variabilità tra le medie dei cluster. Quindi possiamo parametrizzare il modello in modo che ci sia una media generale (come nel **complete-pooling**) ma che sia chiaro come ogni cluster/soggetto si collochi rispetto alla media generale.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ndat |> \n    # media generale\n    mutate(gm = mean(Reaction)) |> \n    group_by(Subject) |> \n    # media di ogni soggetto\n    mutate(cm = mean(Reaction)) |>\n    ungroup() |> \n    ggplot(aes(x = Subject, y = Reaction)) +\n    geom_hline(yintercept = mean(dat$Reaction)) +\n    geom_segment(aes(x = Subject, xend = Subject, y = gm, yend = cm), col = \"dodgerblue\", lwd = 1) +\n    geom_segment(aes(x = Subject, xend = Subject, y = Reaction, yend = cm),col = \"darkgreen\", position = position_jitter(width = 0.3, seed = 2026)) +\n    geom_point(size = 2, alpha = 0.2, position = position_jitter(width = 0.3, seed = 2026)) +\n    stat_summary(fun = mean, geom = \"point\", size = 5, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=960}\n:::\n:::\n\n\nIn questo grafico vediamo che ogni osservazione può essere scomposta nella sua deviazione rispetto alla media del cluster che a sua volta devia rispetto alla media generale. Quindi, il tempo di reazione del soggetto $i$ nell'osservazione $j$ è:\n\n$$\n\\text{RT}_{ij} = \\overline{\\text{RT}} + \\textcolor{blue}{u_i} + \\textcolor{green}{\\epsilon_{ij}}\n$$\n\nDove quindi la media di ogni soggetto è $\\textcolor{red}{\\overline{\\text{RT}}_i} = \\overline{\\text{RT}} + \\textcolor{blue}{u_i}$. In questo modo, il parametro critico diventa $\\text{Var}(u_i)$ ovvero la variabilità tra le medie dei cluster. Se $\\text{Var}(u_i) \\approx 0$ allora tutte le osservazioni deviano solo rispetto alla media generale $\\overline{\\text{RT}}$ (e siamo nel **complete-pooling**). $\\text{Var}(\\epsilon_{ij})$ rimane sempre, come nel modello lineare, la varianza dei residui.\n\nIl segreto del modello ad effetti misti è quello di fare un **partial-pooling** ovvero non stimare un parametro per soggetto/cluster ma stimare $\\text{Var}(u_i)$ ovvero la variabilità dei cluster attorno alla media generale. Questo permette di tenere conto dei cluster ma di evitare di stimare un parametro per ogni soggetto.\n\nIn termini di modello possiamo scrivere più formalmente:\n\n$$\nRT_{ij} = \\mu_0 + u_i + \\epsilon_{ij}\n$$\n\n$$\nu_i \\sim \\mathcal{N}(0, \\sigma^2_{u})\n$$\n\n$$\n\\epsilon_{ij} \\sim \\mathcal{N}(0, \\sigma^2_{\\epsilon})\n$$\n\nL'assunzione principale (oltre a quelle che già facciamo con il modello lineare classico) è che le deviazioni dei soggetti/cluster rispetto alla media generale siano distributite normalmente. Ora vediamo direttamente come implementarlo in R con il pacchetto `lme4`. La funzione principale è `lme4::lmer()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lme4)\n\nfit <- lmer(Reaction ~ 1 + (1|Subject), data = dat)\nfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: Reaction ~ 1 + (1 | Subject)\n   Data: dat\nREML criterion at convergence: 1904\nRandom effects:\n Groups   Name        Std.Dev.\n Subject  (Intercept) 35.8    \n Residual             44.3    \nNumber of obs: 180, groups:  Subject, 18\nFixed Effects:\n(Intercept)  \n        299  \n\n```\n\n\n:::\n:::\n\n\nLa sintassi è relativamente semplice e divisa in due parti:\n\n- **parte fissa**: `Reaction ~ 1` che identifica la componente sistematica del modello ovvero quelli che abbiamo chiamato effetti fissi. Questa parte viene scritta allo stesso modo di `lm()`.\n- **parte random**: `(1|Subject)` che descrive il clustering, in questo caso rispetto ai soggetti. \n\nLa sintassi per la parte random è leggermente complessa e non molto intuitiva. Sostanzialmente ogni effetto random (ovvero ogni variable che crea dei cluster) ha il suo effetto random. Questo viene aggiunto con `+` alla parte fissa `+ (1|Subject)`. La scrittura è `predittore|cluster` quindi a sinistra di `|` si mette un possibile predittore, in questo caso `1|` indica che abbiamo solo intercetta, nessun predittore. A destra `|cluster` si mette la variabile che identifica i cluster.\n\nLa variabile cluster deve ovviamente essere nel nostro dataset e deve ripetere lo stesso valore per ogni osservazione associata a quel cluster.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(dat, n = 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Reaction Days Subject\n1       250    0     308\n2       259    1     308\n3       251    2     308\n4       321    3     308\n5       357    4     308\n6       415    5     308\n7       382    6     308\n8       290    7     308\n9       431    8     308\n10      466    9     308\n11      223    0     309\n12      205    1     309\n13      203    2     309\n14      205    3     309\n15      208    4     309\n16      216    5     309\n17      214    6     309\n18      218    7     309\n19      224    8     309\n20      237    9     309\n\n```\n\n\n:::\n:::\n\n\nOra vediamo cosa è stato stimato dal modello:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: Reaction ~ 1 + (1 | Subject)\n   Data: dat\n\nREML criterion at convergence: 1904\n\nScaled residuals: \n   Min     1Q Median     3Q    Max \n-2.498 -0.550 -0.148  0.512  3.345 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Subject  (Intercept) 1278     35.8    \n Residual             1959     44.3    \nNumber of obs: 180, groups:  Subject, 18\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept)   298.51       9.05      33\n\n```\n\n\n:::\n:::\n\n\nNel summary del modello vediamo una divisione chiara tra parte fissa e random. La parte fissa è sostanzialmente uguale a quella che otteniamo con `lm`. Abbiamo il parametro stimato, l'errore standard e la statistica test. Una cosa che non abbiamo sono i p value. Questo è un punto critico ma di base, con i modelli mixed-effects il calcolo dei gradi di libertà (necessario per i p value) non è semplice e non c'è un modo univoco.\n\nIl modo più semplice per averli è usare il pacchetto `lmerTest` che usa un'approssimazione per il calcolo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lmerTest)\n# dobbiamo ri-fittare il modello dopo aver caricato il pacchetto perchè lmerTest\n# contiene un wrapper della funzione lmer()\nfit <- lmer(Reaction ~ 1 + (1|Subject), data = dat)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Reaction ~ 1 + (1 | Subject)\n   Data: dat\n\nREML criterion at convergence: 1904\n\nScaled residuals: \n   Min     1Q Median     3Q    Max \n-2.498 -0.550 -0.148  0.512  3.345 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Subject  (Intercept) 1278     35.8    \n Residual             1959     44.3    \nNumber of obs: 180, groups:  Subject, 18\n\nFixed effects:\n            Estimate Std. Error     df t value Pr(>|t|)    \n(Intercept)   298.51       9.05  17.00      33   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n```\n\n\n:::\n:::\n\n\nLa parte più interessante è però quella random:\n\n\n::: {.cell layout-align=\"center\" lines='^Random effects|^Number of obs'}\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Subject  (Intercept) 1278     35.8    \n Residual             1959     44.3    \nNumber of obs: 180, groups:  Subject, 18\n```\n\n\n:::\n:::\n\n\nLa parte `residual` è quella che avremmo ottenuto anche dal modello con `lm` e rappresenta $\\sigma^2_{\\epsilon}$ ovvero la variabilità dei residui. Invece la parte `subject` è la stima di $\\sigma^2_{u}$ ovvero della variazione attorno alla media generale.\n\nQuesto modello è detto *random-intercept model* perchè consente ad ogni cluster/soggetto di avere la sua media ed è espressa come deviazione rispetto alla media generale `(Intercept)`.\n\nPossiamo anche calcolare l'ICC in modo più accurato ovvero usando le componenti di varianza calcolate dal modello.\n\n$$\n\\mbox{ICC} = \\frac{\\sigma^2_{u}}{\\sigma^2_{u} + \\sigma^2_{\\epsilon}}\n$$\n\nOvvero la varianza delle intercette di ogni cluster/soggetto sulla variabilità totale. Possiamo usare il pacchetto `performance` ed il pacchetto `insight` per estrarre informazioni utili da questi modelli.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# la funzione get_variance estrae tutte le componenti di varianza dal modello\n(v <- insight::get_variance(fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$var.fixed\n[1] 0\n\n$var.random\n[1] 1278\n\n$var.residual\n[1] 1959\n\n$var.distribution\n[1] 1959\n\n$var.dispersion\n[1] 0\n\n$var.intercept\nSubject \n   1278 \n\n```\n\n\n:::\n\n```{.r .cell-code}\nv$var.intercept / (v$var.intercept + v$var.residual)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSubject \n  0.395 \n\n```\n\n\n:::\n\n```{.r .cell-code}\n# oppure direttamente con la funzione performance::icc()\nperformance::icc(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Intraclass Correlation Coefficient\n\n    Adjusted ICC: 0.395\n  Unadjusted ICC: 0.395\n\n```\n\n\n:::\n:::\n\n\nQuesta è la stima più accurata di quello che avevamo calcolato a mano in precendenza. Questo significa che il 40% della variabilità totale è spiegata/dovuta al clustering delle osservazioni dentro i soggetti. Vediamo la differenza con il modello con `lm()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_lm <- lm(Reaction ~ 1, data = dat)\nsummary(fit_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Reaction ~ 1, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-104.18  -43.13   -9.86   38.24  167.85 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    298.5        4.2    71.1   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 56.3 on 179 degrees of freedom\n\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Reaction ~ 1 + (1 | Subject)\n   Data: dat\n\nREML criterion at convergence: 1904\n\nScaled residuals: \n   Min     1Q Median     3Q    Max \n-2.498 -0.550 -0.148  0.512  3.345 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Subject  (Intercept) 1278     35.8    \n Residual             1959     44.3    \nNumber of obs: 180, groups:  Subject, 18\n\nFixed effects:\n            Estimate Std. Error     df t value Pr(>|t|)    \n(Intercept)   298.51       9.05  17.00      33   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n```\n\n\n:::\n:::\n\n\nCome vedete, la stima dell'intercetta generale (quindi i tempi di reazione medi) è praticamente identica tra i due modelli. Quello che è drasticamente diverso è l'errore standard. Se notate, la differenza è simile a quella che avevamo calcolato a mano. Ignorando il clustering, abbiamo una sovrastima della precisione dovuta ad aver violato l'assunzione di indipendenza delle osservazioni.\n\nUna cosa che possiamo fare ora è stimare il punteggio medio di ogni soggetto che sarà quindi $\\beta_0 + u_i$ ovvero l'intercetta generale più la deviazione soggetto-specifica. Possiamo ottenere queste stime con la funzione `ranef()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# queste le stime dei parametri fissi beta_0\n(fe <- fixef(fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n        299 \n\n```\n\n\n:::\n\n```{.r .cell-code}\n# queste sono le stime di u_i\n(re <- ranef(fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Subject\n    (Intercept)\n308       37.83\n309      -72.21\n310      -58.54\n330        4.09\n331        9.48\n332        7.63\n333       15.31\n334       -2.78\n335      -42.00\n337       66.95\n349      -19.66\n350       13.09\n351       -7.29\n352       33.74\n369        6.53\n370       -5.90\n371       -3.06\n372       16.80\n\nwith conditional variances for \"Subject\" \n\n```\n\n\n:::\n\n```{.r .cell-code}\nb0 <- fe[1]\nu <- re$Subject[, 1]\nby_subj <- data.frame(b0 = b0, u = u, yi = b0 + u)\nby_subj\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    b0      u  yi\n1  299  37.83 336\n2  299 -72.21 226\n3  299 -58.54 240\n4  299   4.09 303\n5  299   9.48 308\n6  299   7.63 306\n7  299  15.31 314\n8  299  -2.78 296\n9  299 -42.00 257\n10 299  66.95 365\n11 299 -19.66 279\n12 299  13.09 312\n13 299  -7.29 291\n14 299  33.74 332\n15 299   6.53 305\n16 299  -5.90 293\n17 299  -3.06 295\n18 299  16.80 315\n\n```\n\n\n:::\n:::\n\n\nUn'altro modo più efficiente di ottere le stime è usare la funzione `coeff()` che fornisce direttamente la stima come combinazione lineare di parametri fissi e random.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Subject\n    (Intercept)\n308         336\n309         226\n310         240\n330         303\n331         308\n332         306\n333         314\n334         296\n335         257\n337         365\n349         279\n350         312\n351         291\n352         332\n369         305\n370         293\n371         295\n372         315\n\nattr(,\"class\")\n[1] \"coef.mer\"\n\n```\n\n\n:::\n:::\n\n\nConfrontiamo queste stime con quelle ottenute dal modello **no-pooling** quindi stimando direttamente un parametro per ogni soggetto:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nre_comp <- data.frame(no_pool = coef(fit_no_pool), lmer = coef(fit)$Subject[, 1])\nre_comp$subject <- gsub(\"Subject\", \"\", rownames(re_comp))\nre_comp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           no_pool lmer subject\nSubject308     342  336     308\nSubject309     215  226     309\nSubject310     231  240     310\nSubject330     303  303     330\nSubject331     309  308     331\nSubject332     307  306     332\nSubject333     316  314     333\nSubject334     295  296     334\nSubject335     250  257     335\nSubject337     376  365     337\nSubject349     276  279     349\nSubject350     314  312     350\nSubject351     290  291     351\nSubject352     337  332     352\nSubject369     306  305     369\nSubject370     292  293     370\nSubject371     295  295     371\nSubject372     318  315     372\n\n```\n\n\n:::\n:::\n\n\nIntanto si vede che le stime non sono identiche ma generalmente molto simili.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nre_comp |> \n    pivot_longer(c(no_pool, lmer)) |>\n    ggplot(aes(x = subject, y = value, color = name)) +\n    geom_point() +\n    geom_hline(yintercept = fixef(fit)[1])\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nDal grafico vediamo un concetto molto importante ovvero quello dello *shrinkage*. Come vedete, le stime fatte dal modello con `lmer` sono sistematicamente minori. In termini fisici è come se fossero più attirate verso il centro (la stima dell'effetto medio, linea nera) rispetto a quelle con il modello `lm` (un parametro per soggetto).\n\nVediamo anche che lo *shrinkage* non è casuale, né necessariamente uguale per tutti i gruppi. Nel caso più semplice di un modello a intercetta variabile,\n\n$$\ny_{ij} = \\mu + u_j + \\varepsilon_{ij}\n$$\n\ncon:\n\n$$\nu_j \\sim N(0,\\tau^2)\n$$\n\ne\n\n$$\n\\varepsilon_{ij} \\sim N(0,\\sigma^2)\n$$\n\nla stima della media del gruppo $j$ può essere scritta come:\n\n$$\n\\hat{\\mu}_j =\n\\hat{\\mu} + \\lambda_j(\\bar{y}_j - \\hat{\\mu})\n$$\n\ndove $\\bar{y}_j$ è la media grezza del gruppo $j$, $\\hat{\\mu}$ è la media globale stimata e $\\lambda_j$ è un peso compreso tra 0 e 1:\n\n$$\n\\lambda_j =\n\\frac{\\tau^2}{\\tau^2 + \\sigma^2/n_j}\n$$\n\nLa stessa espressione può essere riscritta come media pesata tra la media globale e la media osservata del gruppo:\n\n$$\n\\hat{\\mu}_j =\n(1-\\lambda_j)\\hat{\\mu} + \\lambda_j \\bar{y}_j\n$$\n\nQuindi la stima del gruppo non coincide necessariamente con la sua media grezza: è una stima intermedia tra la media globale e la media del gruppo. Il peso $\\lambda_j$ misura quanto il modello si fida dell’informazione specifica del gruppo.\n\nSe $\\lambda_j$ è vicino a 1, la stima del gruppo sarà molto vicina a $\\bar{y}_j$. Se invece $\\lambda_j$ è vicino a 0, la stima del gruppo sarà molto vicina a $\\hat{\\mu}$.\n\n### Casi limite\n\nSe il gruppo ha molte osservazioni, cioè se $n_j$ è molto grande, allora:\n\n$$\n\\frac{\\sigma^2}{n_j} \\to 0\n$$\n\ne quindi:\n\n$$\n\\lambda_j \\to\n\\frac{\\tau^2}{\\tau^2 + 0}\n=\n1\n$$\n\nIn questo caso:\n\n$$\n\\hat{\\mu}_j\n\\to\n\\bar{y}_j\n$$\n\nIl modello si fida molto della media osservata del gruppo e lo shrinkage tende a scomparire.\n\nAl contrario, se il gruppo ha poche osservazioni, il termine $\\sigma^2/n_j$ rimane più grande. Di conseguenza, $\\lambda_j$ diminuisce e la stima del gruppo viene tirata maggiormente verso la media globale.\n\nAnche la varianza tra gruppi è importante. Se $\\tau^2$ è molto piccola, il modello conclude che i gruppi non differiscono molto tra loro:\n\n$$\n\\lambda_j \\to 0\n$$\n\ne quindi:\n\n$$\n\\hat{\\mu}_j \\to \\hat{\\mu}\n$$\n\nLe stime dei gruppi collassano verso la media globale.\n\nSe invece $\\tau^2$ è grande rispetto a $\\sigma^2/n_j$, il modello riconosce molta variabilità reale tra gruppi. In questo caso $\\lambda_j$ è più vicino a 1 e lo shrinkage è più debole.\n\n### Interpretazione\n\nLo shrinkage aumenta quando:\n\n$$\nn_j \\downarrow\n$$\n\ncioè quando il gruppo ha poche osservazioni;\n\n$$\n\\sigma^2 \\uparrow\n$$\n\ncioè quando c’è molta variabilità residua entro gruppo;\n\n$$\n\\tau^2 \\downarrow\n$$\n\ncioè quando i gruppi sembrano poco diversi tra loro.\n\nAl contrario, lo shrinkage diminuisce quando il gruppo ha molte osservazioni, quando la variabilità residua è bassa e quando il modello riconosce una forte variabilità reale tra gruppi.\n\nÈ importante distinguere tra shrinkage proporzionale e shrinkage assoluto. Se due gruppi hanno lo stesso numero di osservazioni, lo stesso modello applica la stessa proporzione di shrinkage. Tuttavia, un gruppo più lontano dalla media globale viene spostato di più in termini assoluti, semplicemente perché la sua distanza iniziale è maggiore.\n\nInfatti:\n\n$$\n\\bar{y}_j - \\hat{\\mu}_j =\n(1-\\lambda_j)(\\bar{y}_j - \\hat{\\mu})\n$$\n\nPer esempio, se $\\lambda_j = .70$, il modello conserva il 70% della deviazione del gruppo dalla media globale e ne riduce il 30%. Se un gruppo dista 10 dalla media globale, lo spostamento sarà 3; se un gruppo dista 100, lo spostamento sarà 30. Il secondo gruppo viene quindi trascinato di più in termini assoluti, ma non in termini proporzionali.\n\nIn sintesi, lo shrinkage è una forma di **partial pooling**: il mixed model non usa solo la media del singolo gruppo, come farebbe una stima completamente separata, ma non ignora nemmeno le differenze tra gruppi, come farebbe un modello completamente aggregato. Produce invece una stima intermedia, tanto più vicina alla media del gruppo quanto più l’informazione su quel gruppo è precisa.\n\n## Modello con predittori\n\nVediamo ora cosa succede aggiungendo il predittore `Days` nel modello con intercetta random. Partiamo dal modello in R e poi formalizziamo quello che succede:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_days <- lmer(Reaction ~ 1 + Days + (1|Subject), data = dat)\nsummary(fit_days, cor = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Reaction ~ 1 + Days + (1 | Subject)\n   Data: dat\n\nREML criterion at convergence: 1786\n\nScaled residuals: \n   Min     1Q Median     3Q    Max \n-3.226 -0.553  0.011  0.519  4.251 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Subject  (Intercept) 1378     37.1    \n Residual              960     31.0    \nNumber of obs: 180, groups:  Subject, 18\n\nFixed effects:\n            Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)  251.405      9.747  22.810    25.8   <2e-16 ***\nDays          10.467      0.804 161.000    13.0   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n```\n\n\n:::\n:::\n\n\nOra abbiamo anche l'effetto fisso di `Days` che ovviamente intepretiamo allo stesso modo di un modello con `lm`. Confrontiamolo comunque con la stima che ignora i cluster:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_days_lm <- lm(Reaction ~ Days, data = dat)\nsummary(fit_days_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Reaction ~ Days, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-110.85  -27.48    1.55   26.14  139.95 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   251.41       6.61   38.03  < 2e-16 ***\nDays           10.47       1.24    8.45  9.9e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 47.7 on 178 degrees of freedom\nMultiple R-squared:  0.286,\tAdjusted R-squared:  0.282 \nF-statistic: 71.5 on 1 and 178 DF,  p-value: 9.89e-15\n\n```\n\n\n:::\n\n```{.r .cell-code}\n# la funzione car::compareCoefs è molto utile per \n# confrontare visivamente le stime di modelli diversi\ncar::compareCoefs(fit_days, fit_days_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCalls:\n1: lmer(formula = Reaction ~ 1 + Days + (1 | Subject), data = dat)\n2: lm(formula = Reaction ~ Days, data = dat)\n\n            Model 1 Model 2\n(Intercept)  251.41  251.41\nSE             9.75    6.61\n                           \nDays         10.467  10.467\nSE            0.804   1.238\n                           \n\n```\n\n\n:::\n:::\n\n\nVediamo lo stesso pattern del modello precedente, le stime degli effetti fissi sono praticamente identiche ma gli standard error sono decisamente maggiori nel modello con `lmer` (nulla di nuovo).\n\nIl modello con `lm` sta stimando un'intercetta comune a tutti e una slope/pendenza comune a tutti. Il modello `fit_days` invece incorpora il clustering dei soggetti stimando un'intercetta specifica per ogni soggetto. Vediamo graficamente:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estraiamo i coefficienti\ncoefs_lmer <- data.frame(coef(fit_days)$Subject)\nnames(coefs_lmer) <- c(\"b0\", \"b1\")\ncoefs_lmer$b0_lm <- coef(fit_days_lm)[1]\ncoefs_lmer$b1_lm <- coef(fit_days_lm)[2]\ncoefs_lmer$Subject <- rownames(coefs_lmer)\nhead(coefs_lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     b0   b1 b0_lm b1_lm Subject\n308 292 10.5   251  10.5     308\n309 174 10.5   251  10.5     309\n310 188 10.5   251  10.5     310\n330 256 10.5   251  10.5     330\n331 262 10.5   251  10.5     331\n332 260 10.5   251  10.5     332\n\n```\n\n\n:::\n\n```{.r .cell-code}\n# ora espandiamo con i Days\n\ncoefs_lmer <- expand_grid(coefs_lmer, Days = 0:9)\nhead(coefs_lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n     b0    b1 b0_lm b1_lm Subject  Days\n  <dbl> <dbl> <dbl> <dbl> <chr>   <int>\n1  292.  10.5  251.  10.5 308         0\n2  292.  10.5  251.  10.5 308         1\n3  292.  10.5  251.  10.5 308         2\n4  292.  10.5  251.  10.5 308         3\n5  292.  10.5  251.  10.5 308         4\n6  292.  10.5  251.  10.5 308         5\n\n```\n\n\n:::\n\n```{.r .cell-code}\n# calcoliamo i valori\ncoefs_lmer$y_lm <- with(coefs_lmer, b0_lm + b1_lm * Days)\ncoefs_lmer$y_lmer <- with(coefs_lmer, b0 + b1 * Days)\n\nhead(coefs_lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n     b0    b1 b0_lm b1_lm Subject  Days  y_lm y_lmer\n  <dbl> <dbl> <dbl> <dbl> <chr>   <int> <dbl>  <dbl>\n1  292.  10.5  251.  10.5 308         0  251.   292.\n2  292.  10.5  251.  10.5 308         1  262.   303.\n3  292.  10.5  251.  10.5 308         2  272.   313.\n4  292.  10.5  251.  10.5 308         3  283.   324.\n5  292.  10.5  251.  10.5 308         4  293.   334.\n6  292.  10.5  251.  10.5 308         5  304.   345.\n\n```\n\n\n:::\n\n```{.r .cell-code}\ncoefs_lmer |> \n    pivot_longer(c(y_lm, y_lmer)) |> \n    ggplot(aes(x = Days, y = value, color = Subject)) +\n    geom_line() +\n    facet_wrap(~name)\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-32-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nQuello che si vede è che la pendenza rimane la stessa per ogni soggetto in entrambi i modelli. Tuttavia nel modello con `lmer` ogni soggetto ha la sua intercetta e quindi una parte di variabilità viene catturata dal termine random. \n\nIn termini pratici stiamo introducendo nel modello le differenze individuali nei termini che ogni soggetto ha il suo tempo di reazione medio di partenza.\n\nIn termini più formali, il nostro modello ora diventa:\n\n$$\ny_{ij} = \\beta_0 + u_i + \\beta_1 \\text{Days}_{ij} + \\epsilon_{ij}\n$$\n\n\n::: {.callout-tip}\n\nUn trucco per leggere le formule dei modelli con effetti random riguarda il guardare i subscript $i$, $j$, etc. Se $i$ sono i soggetti, ogni volta che vediamo $i$ significa che quel termine *varia* tra soggetti. Nel nostro caso $u_i$ significa che ogni soggetto può avere un $u$ diverso ovvero una deviazione rispetto la media generale.\n\nAllo stesso modo $ij$ significa che quel valore può variare per ogni combinazione di $i$ (soggetto) e $j$ giorno di deprivazione.\n\nAl contrario, per ora, $\\beta_1$ non ha nessun subscript quindi il valore è fisso (effetto fisso) per ogni osservazione nel dataset.\n:::\n\nSe riguardiamo i grafici iniziali però ci accorgiamo che non solo i soggetti hanno il loro tempo di reazione medio ma anche l'impatto della deprivazione è diverso tra soggetti. Per modellare questo aspetto possiamo permettere al modello di mettere il subscript $i$ anche su $\\beta_1$ e non solo su $\\beta_0$.\n\nVediamo anche qui prima in R e poi più formalmente. Per aggiungere la **random slope** per `Days` dobbiamo includere `Days` sia nella parte fissa (come ora) che in quella random:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_days_slopes <- lmer(Reaction ~ 1 + Days + (1 + Days | Subject), data = dat)\nsummary(fit_days_slopes, cor = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Reaction ~ 1 + Days + (1 + Days | Subject)\n   Data: dat\n\nREML criterion at convergence: 1744\n\nScaled residuals: \n   Min     1Q Median     3Q    Max \n-3.954 -0.463  0.023  0.463  5.179 \n\nRandom effects:\n Groups   Name        Variance Std.Dev. Corr \n Subject  (Intercept) 612.1    24.74         \n          Days         35.1     5.92    0.07 \n Residual             654.9    25.59         \nNumber of obs: 180, groups:  Subject, 18\n\nFixed effects:\n            Estimate Std. Error     df t value Pr(>|t|)    \n(Intercept)   251.41       6.82  17.00   36.84  < 2e-16 ***\nDays           10.47       1.55  17.00    6.77  3.3e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n```\n\n\n:::\n:::\n\n\nVediamo che la parte fissa è rimasta la stessa in termini di parametri stimati mentre quella random è diventata più complessa. Nella sezione random effects:\n\n- `(Intercept)`: è la varianza delle intercette (come nel modello precedente). Indica quanto la media dei soggetti varia attorno alla media generale.\n- `(Days)`: è la varianza delle slopes (questa è la novità). Indica quanto le slopes dei soggetti variano rispetto alla slope generale.\n\nLa cosa migliore è vederlo subito graficamente e poi passiamo ai valori specifici:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef_lmer_days <- data.frame(coef(fit_days)$Subject)\ncoef_lmer_days_slopes <- data.frame(coef(fit_days_slopes)$Subject)\ncoef_lmer_days$model <- \"(1 | Subject)\"\ncoef_lmer_days_slopes$model <- \"(1 + Days|Subject)\"\ncoef_lmer_days$Subject <- rownames(coef_lmer_days)\ncoef_lmer_days_slopes$Subject <- rownames(coef_lmer_days_slopes)\ncoef_lmer_days <- rbind(coef_lmer_days, coef_lmer_days_slopes)\nnames(coef_lmer_days) <- c(\"b0\", \"b1\", \"model\", \"subject\")\n\nhead(coef_lmer_days)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     b0   b1         model subject\n308 292 10.5 (1 | Subject)     308\n309 174 10.5 (1 | Subject)     309\n310 188 10.5 (1 | Subject)     310\n330 256 10.5 (1 | Subject)     330\n331 262 10.5 (1 | Subject)     331\n332 260 10.5 (1 | Subject)     332\n\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef_lmer_days |> \n    expand_grid(Days = 0:9) |>\n    mutate(y = b0 + b1 * Days) |>  \n    ggplot(aes(x = Days, y = y, color = subject, group = subject)) +\n    facet_wrap(~model) +\n    geom_line()\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-34-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nVediamo adesso che oltre all'intercetta, anche la pendenza adesso è soggetto-specifica. Questo si vede chiaramente estraendo i coefficienti:\n\n\n::: {.columns}\n\n::: {.column}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# intercette random\ncoef(fit_days)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Subject\n    (Intercept) Days\n308         292 10.5\n309         174 10.5\n310         188 10.5\n330         256 10.5\n331         262 10.5\n332         260 10.5\n333         268 10.5\n334         248 10.5\n335         206 10.5\n337         324 10.5\n349         230 10.5\n350         266 10.5\n351         244 10.5\n352         288 10.5\n369         258 10.5\n370         245 10.5\n371         248 10.5\n372         270 10.5\n\nattr(,\"class\")\n[1] \"coef.mer\"\n\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# intercette e slope random\ncoef(fit_days_slopes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Subject\n    (Intercept)   Days\n308         254 19.666\n309         211  1.848\n310         212  5.018\n330         275  5.653\n331         274  7.397\n332         260 10.195\n333         268 10.244\n334         244 11.542\n335         251 -0.285\n337         286 19.096\n349         226 11.641\n350         238 17.082\n351         256  7.452\n352         272 14.003\n369         255 11.340\n370         226 15.290\n371         252  9.479\n372         264 11.751\n\nattr(,\"class\")\n[1] \"coef.mer\"\n\n```\n\n\n:::\n:::\n\n\n:::\n\n:::\n\nL'altra differenza importante riguarda sempre gli errori standard. Nel modello che ignora le random slopes, la precisione nella stima di $\\beta_1$ è molto più elevata (artificiosamente):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncar::compareCoefs(fit_days, fit_days_slopes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCalls:\n1: lmer(formula = Reaction ~ 1 + Days + (1 | Subject), data = dat)\n2: lmer(formula = Reaction ~ 1 + Days + (1 + Days | Subject), data = dat)\n\n            Model 1 Model 2\n(Intercept)  251.41  251.41\nSE             9.75    6.82\n                           \nDays         10.467  10.467\nSE            0.804   1.546\n                           \n\n```\n\n\n:::\n:::\n\n\nUn ultimo termine che compare nei parametri random stimati è la correlazione:\n\n\n::: {.cell layout-align=\"center\" lines='^Random|^ Residual'}\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom effects:\n Groups   Name        Variance Std.Dev. Corr \n Subject  (Intercept) 612.1    24.74         \n          Days         35.1     5.92    0.07 \n Residual             654.9    25.59         \n```\n\n\n:::\n:::\n\n\nQuel termine rappresenta la correlazione stimata tra intercette e slopes random. Con le formule sarà più chiaro ma in termini interpretativi rappresenta la tendenza di soggetti con tempi di reazione medi maggiori ad avere anche un effetto di `Days` maggiore (nel caso di correlazione positiva oppure l'inverso). In questo caso sembra che intercette e slopes non siano correlate.\n\nLa parte random può essere complicata da stimare a volte e quindi è possibile porre dei vincoli. Nel nostro caso possiamo fissare la correlazione a zero (ovvero non farla stimare al modello):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_days_slopes_0 <- lmer(Reaction ~ 1 + Days + (1 + Days || Subject), data = dat)\nsummary(fit_days_slopes_0, cor = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Reaction ~ 1 + Days + (1 + Days || Subject)\n   Data: dat\n\nREML criterion at convergence: 1744\n\nScaled residuals: \n   Min     1Q Median     3Q    Max \n-3.963 -0.463  0.020  0.465  5.186 \n\nRandom effects:\n Groups    Name        Variance Std.Dev.\n Subject   (Intercept) 627.6    25.05   \n Subject.1 Days         35.9     5.99   \n Residual              653.6    25.57   \nNumber of obs: 180, groups:  Subject, 18\n\nFixed effects:\n            Estimate Std. Error     df t value Pr(>|t|)    \n(Intercept)   251.41       6.89  18.16   36.51  < 2e-16 ***\nDays           10.47       1.56  18.16    6.71  2.6e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n```\n\n\n:::\n:::\n\n\nEssendo che viene stimata praticamente a zero, il fissarla a priori non fa cambiare molto. Possiamo anche formalmente comparare i modelli usando un likelihood-ratio test con la funzione `anova()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(fit_days, fit_days_slopes_0, fit_days_slopes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: dat\nModels:\nfit_days: Reaction ~ 1 + Days + (1 | Subject)\nfit_days_slopes_0: Reaction ~ 1 + Days + (1 + Days || Subject)\nfit_days_slopes: Reaction ~ 1 + Days + (1 + Days | Subject)\n                  npar  AIC  BIC logLik -2*log(L) Chisq Df Pr(>Chisq)    \nfit_days             4 1802 1815   -897      1794                        \nfit_days_slopes_0    5 1762 1778   -876      1752 42.08  1    8.8e-11 ***\nfit_days_slopes      6 1764 1783   -876      1752  0.06  1        0.8    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n```\n\n\n:::\n:::\n\n\nIl primo confronto valuta se l’aggiunta della random slope per Days migliora il modello rispetto al modello con sola intercetta random. Il secondo confronto valuta se, una volta inclusa la random slope, sia utile stimare anche la correlazione tra intercetta e slope random. In questo caso i modelli hanno la stessa parte fissa e differiscono solo nella struttura random.\n\nEssendo la correlazione praticamente a zero, il confronto tra modelli ci dice che il modello migliore è quello che include le random slopes ma esclude la correlazione tra intercette e slopes.\n\nVediamo adesso formalmente il modello:\n\n$$\ny_{ij} = \\beta_0 + u_i + (\\beta_1 + b_i)\\text{Days}_{ij} + \\epsilon_{ij}\n$$\n\n$$\nu_i, b_i \\sim \\mathcal{N}(\\mathbf{0}, \\Sigma)\n$$\n\n$$\n\\Sigma = \n\\begin{bmatrix}\n\\sigma^2_{u_i} & \\rho \\sigma_{u_i} \\sigma_{b_i}  \\\\\n\\rho \\sigma_{u_i} \\sigma_{b_i} & \\sigma^2_{b_i}\n\\end{bmatrix}\n$$\n\nQuindi le intercette e slopes random vengono da una distribuzione normale multivariata con matrice di varianza-covarianza $\\Sigma$.\n\n\n::: {.callout-note title=\"Distribuzione normale multivariata\" collapse=\"true\"}\n\nSe non siete familari con le distribuzioni normali multivariate e matrici di varianza-covarianza facciamo un piccolo approfondimento. La distribuzione normale è definita per media $\\mu$ e varianza $\\sigma^2$ ed è una distribuzione univariata.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# normale con media 0 e sd 1\nx <- rnorm(10, mean = 0, sd = 1)\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] -0.49855  0.42054 -1.66931  0.00303  0.42816  0.71316  1.22587 -1.70461\n [9] -1.07823  0.63469\n\n```\n\n\n:::\n:::\n\n\nOra se utilizzo due distribuzioni normali con le rispettive medie e varianze sto, implicitamente, dicendo che le due normali sono indipendenti ovvero che la loro correlazione è zero.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ny <- rnorm(10, mean = 5, sd = 2)\ny\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 1.99 6.89 3.84 6.68 1.54 7.73 2.61 4.74 3.48 2.69\n\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(x, y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.058\n\n```\n\n\n:::\n:::\n\n\nTuttavia potrei voler inserire una correlazione tra le due distribuzioni e quindi mettere oltre alle due medie e varianze anche la correlazione. Per questo caso possiamo definire una matrice di varianza covarianza $\\Sigma$ che descrive le varianze delle due (o più) distribuzioni normali e la(e) loro correlazione(i).\n\n$$\n\\Sigma =\n\\begin{bmatrix}\n\\sigma_x^2 & \\rho \\sigma_x \\sigma_y \\\\\n\\rho \\sigma_x \\sigma_y & \\sigma_y^2\n\\end{bmatrix}\n$$\n\nDove $\\rho$ è la correlazione e quindi $\\rho \\sigma_x \\sigma_y$ è la covarianza.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# deviazione standard di x e y\ns <- c(1, 2)\n# correlazione ipotetica\nr <- 0.5\n# matrice di correlazione\nR <- r + diag(1 - r, 2)\nR\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2]\n[1,]  1.0  0.5\n[2,]  0.5  1.0\n\n```\n\n\n:::\n\n```{.r .cell-code}\n# matrice di varianza-covarianza\nS <- diag(s) %*% R %*% diag(s)\nS\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2]\n[1,]    1    1\n[2,]    1    4\n\n```\n\n\n:::\n:::\n\n\nOra possiamo generare dati non con `rnorm` ma con `MASS::mvrnorm()` che gestisce il caso multivariato. L'unico ingrediente che manca sono le medie. Nel nostro caso, ogni normale ha la sua media che possiamo descrivere in modo compatto con un vettore.\n\n$$\n\\mathbf{y} \\sim \\mathcal{N} \\left(\n\\begin{bmatrix}\n\\mu_1 \\\\\n\\mu_2\n\\end{bmatrix},\n\\Sigma\n\\right)\n$$\n\nQuindi:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# vettore di medie\nmu <- c(0, 0)\n\n# cosi generiamo due distribuzioni normali correlate\nMASS::mvrnorm(10, mu = mu, Sigma = S)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]   [,2]\n [1,]  1.2164  2.020\n [2,] -0.1731 -1.328\n [3,]  0.5856 -2.175\n [4,]  2.4346 -1.219\n [5,]  0.0801 -0.318\n [6,] -3.0136 -5.372\n [7,] -1.3987 -0.782\n [8,] -1.9533 -4.013\n [9,]  0.7425  0.674\n[10,] -0.8033 -2.136\n\n```\n\n\n:::\n:::\n\n\n:::\n\nQuindi tramite la formula `(1|Subject)` possiamo rendere più o meno complessa la distribuzione normale multivariata che descrive gli effetti random. Ad esempio, facendo `(1|Subject)` stiamo sostanzialmente facendo:\n\n$$\n\\Sigma = \n\\begin{bmatrix}\n\\sigma^2_{u_i}\n\\end{bmatrix}\n$$\n\nOvvero una singola distribuzione normale. Mentre `(Days||Subject)` stiamo imponendo gli elementi off-diagonal (fuori dalla diagonale) ad essere zero:\n\n$$\n\\Sigma = \n\\begin{bmatrix}\n\\sigma^2_{u_i} & 0  \\\\\n0 & \\sigma^2_{b_i}\n\\end{bmatrix}\n$$\n\nOra vediamo qualche modo di avere informazioni aggiuntive rispetto al modello stimato che vadano oltre quello che `summary()` riporta.\n\nPossiamo estrarre gli intervalli di confidenza con il comando `confint()`. La prima opzione è chiamata Wald confidence intervals. Questi non sono altro che dei semplici intervalli di confidenza basati sull'approssimazione normale della distrubuzione campionaria. In formula questo equivale a:\n\n$$\n95\\% CI = \\hat \\beta \\pm q \\text{SE}_{\\beta}\n$$\n\nDove $q$ è il quantile critico al livello $\\alpha$ per la distribuzione campionaria che si assume. Ad esempio, per la distribuzione normale con $\\alpha = 0.05$ il quantile critico è $q \\approx 1.96$. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# con la funzione\nconfint(fit_days_slopes, method = \"Wald\", level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             2.5 % 97.5 %\n.sig01          NA     NA\n.sig02          NA     NA\n.sig03          NA     NA\n.sigma          NA     NA\n(Intercept) 238.03  264.8\nDays          7.44   13.5\n\n```\n\n\n:::\n\n```{.r .cell-code}\n# manualmente\n(q <- abs(qnorm(0.05/2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.96\n\n```\n\n\n:::\n\n```{.r .cell-code}\n# estraggo gli standard error\nb <- fixef(fit_days_slopes)\nse <- summary(fit_days_slopes)$coefficients[, \"Std. Error\"]\n\n# lower\nb - q * se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)        Days \n     238.03        7.44 \n\n```\n\n\n:::\n\n```{.r .cell-code}\n# upper\nb + q * se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)        Days \n      264.8        13.5 \n\n```\n\n\n:::\n:::\n\n\nL'altra opzione che è anche il default riguarda l'utilizzo dei profile likelihood confidence intervals. Questo tipo di intervalli sono basati sulla likelihood della stima dei parametri:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# estraggo prima le likelihood perchè ci mette molto, altrimenti direttamente con\n# confint(fit)\npf <- profile(fit_days_slopes)\nconfint(pf, method = \"profile\", level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              2.5 %  97.5 %\n.sig01       14.381  37.716\n.sig02        3.801   8.753\n.sig03       -0.482   0.685\n.sigma       22.898  28.858\n(Intercept) 237.681 265.130\nDays          7.359  13.576\n\n```\n\n\n:::\n:::\n\n\nQuesto è il grafico delle profile likelihoo di ogni parametro. L'intervallo di confidenza in questo caso si calcola direttamente sulla profile likelihood e potrebbe essere diverso dalla versione Wald oltre a non essere necessariamente simmetrico.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlattice::densityplot(pf)\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-47-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nVediamo adesso come rappresentare graficamente gli effetti random:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlattice::dotplot(ranef(fit_days_slopes))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Subject\n\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-48-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nQuesti grafici sono molto utili per avere un'idea più concreta, ad intepretare le varianze stimate, rispetto a quanto variano i parametri tra soggetti. Ad esempio mentre chiaro che l'intercetta è molto diversa tra soggetti, la slope seppur con delle differenze sembrebbe essere più simile (a parte alcuni soggetti).\n\nOra vediamo come rappresentare graficamente ed in formato tabella il nostro modello. Per gli effetti fissi possiamo usare il pacchetto `ggeffects()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggeffects)\n\nggeffect(fit_days_slopes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Days\n# Predicted values of Reaction\n\nDays | Predicted |         95% CI\n---------------------------------\n   0 |    251.41 | 237.94, 264.87\n   1 |    261.87 | 248.48, 275.27\n   2 |    272.34 | 258.34, 286.34\n   3 |    282.81 | 267.60, 298.01\n   5 |    303.74 | 284.83, 322.65\n   6 |    314.21 | 293.03, 335.39\n   7 |    324.68 | 301.05, 348.30\n   9 |    345.61 | 316.74, 374.48\n\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nattr(,\"class\")\n[1] \"ggalleffects\" \"list\"        \nattr(,\"model.name\")\n[1] \"fit_days_slopes\"\n\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# restituisce un oggetto ggplot che si può customizzare\n# ulteriormente con + ...\nplot(ggeffect(fit_days_slopes))\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-50-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nIn questo caso stiamo plottando l'effetto fisso di `Days` ed il suo intervallo di confidenza in un modello che però tiene conto delle differenze tra soggetti sia nella baseline che nell'effetto della deprivazione.\n\nVediamo adesso nel modello completo l'effetto dello shrinkage per entrambi i parametri stimati. Il centro del grafico è la stima di `lme4` mentre i punti sono le stime con `lm` una per soggetto e le stime di `lme4` ricostruite unendo effetti random e fissi: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfitl <- lmList(Reaction ~ Days | Subject, data = dat)\nres_no_pool <- coef(fitl)\nres_p_pool <- data.frame(coef(fit_days_slopes)$Subject)\nnames(res_no_pool) <- c(\"b0\", \"b1\")\nnames(res_p_pool) <- c(\"b0\", \"b1\")\nres_no_pool$subject <- rownames(res_no_pool)\nres_p_pool$subject <- rownames(res_p_pool)\nres_no_pool$model <- \"lm\"\nres_p_pool$model <- \"lmer\"\nres <- rbind(res_no_pool, res_p_pool)\n\nggplot(res, aes(x = b0, y = b1)) +\n  geom_line(aes(group = subject)) +\n  geom_point(x = fixef(fit_days_slopes)[1], y = fixef(fit_days_slopes)[2], size = 10) +\n    geom_point(aes(color = model), size = 3)\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-51-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nCome avevamo già visto, le stime di ogni soggetto vengono trascinate verso il centro di gravità ovvero i parametri stimati con `lme4`.\n\nPrima di passare a modelli più complessi vorrei fare un cenno rispetto l'interpretazione di effetti fissi e random. Se ci concentriamo nell'effetto `Days`, quindi $\\beta_1$ lo intepretiamo come l'aumento dei tempi di reazione per ogni giorno che passa di deprivazione da sonno.\n\nOra un punto importante riguarda la distinzione tra $\\beta_1$ stimato con `lm` e $\\beta_1$ stimato con `lme4`. Nel modello lineare classico noi stimiamo $\\beta_1$ inteso come un valore fisso che, in base al numero di osservazioni, verra stimato con più o meno precisione. L'unica fonte di variabilità è $\\epsilon$ che, idealmente, si può ridurre semplicemente aumentando la numerosità campionaria. Ogni soggetto ha lo stesso effetto di `Days`.\n\nNel caso di `lme4`, $\\beta_1$ è l'effetto medio di una distribuzione di effetti veri. Essendo la distribuzione assunta come normale possiamo anche visualizzarla:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nb <- fixef(fit_days_slopes)\nvv <- insight::get_variance(fit_days_slopes)\n\nsd_slope <- sqrt(vv$var.slope)\n\nggplot() +\n  stat_function(\n    fun = dnorm,\n    args = list(mean = b[\"Days\"], sd = sd_slope)\n  ) +\n  geom_vline(\n    xintercept = b[\"Days\"],\n    linetype = \"dashed\"\n  ) +\n  xlim(\n    b[\"Days\"] - 4 * sd_slope,\n    b[\"Days\"] + 4 * sd_slope\n  ) +\n  labs(\n    x = \"Slope soggetto-specifico per Days\",\n    y = \"Densità\")\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-52-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nQuindi, la media dell'effetto vero di `Days` è $\\beta_1$ (stimato con `lme4`) ma alcuni soggetti hanno $\\beta_1 = 0$ mentre altri $\\beta_1 = 20$. Questa è una distizione importante ma sottile, le caso di modelli multilivello gli effetti fissi sono la media di effetti veri la cui distrubuzione (in particolare la deviazione standard) viene stimata.\n\nPer la diagnostica valgono sostanzialmente gli stessi assunti del modello lineare classico e possiamo verificarli (graficamente) allo stesso modo. Il pacchetto `performance` ha diverse funzioni per la diagnostica dei modelli, tra cui anche `lme4`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_model(fit_days_slopes)\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-53-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nL'unica differenza importante può essere riguardo la diagnostica di outlier e punti influenti. Infatti mentre nel modello `lm` la singola osservazione (riga del dataset) veniva valutata, nel modello `lmer` abbiamo cluster di osservazioni. Possiamo usare il pacchetto `influence.ME` che calcola le comuni diagnostiche per outlier e punti influenti ma a livello del cluster. L'unica accortezza riguarda l'aspetto computazionale perchè è necessario fittare il modello togliendo un cluster/soggetto per volta.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(influence.ME)\n\ninfl <- influence(fit_days_slopes, group = \"Subject\")\nhead(cooks.distance(infl))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       [,1]\n308 0.10078\n309 0.18781\n310 0.12612\n330 0.08900\n331 0.05649\n332 0.00569\n\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(dfbetas.estex(infl))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    (Intercept)    Days\n308     -0.0587  0.4489\n309     -0.4109 -0.3099\n310     -0.4276 -0.1583\n330      0.3295 -0.2791\n331      0.2921 -0.1904\n332      0.1050 -0.0323\n\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(infl, which = \"cook\", sort = TRUE)\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-54-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\nplot(infl, which = \"dfbetas\")\n```\n\n::: {.cell-output-display}\n![](01-intro-glmm_files/figure-html/unnamed-chunk-54-2.png){fig-align='center' width=672}\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}